import type { Metadata } from "next";
import { SUSE_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import SpaceBackground from "@/src/components/ui/SpaceBackground";

const suseMono = SUSE_Mono({
  variable: "--font-suse-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${suseMono.variable} h-full antialiased`}>
      <body className="relative flex min-h-full flex-col overflow-x-hidden">
        <SpaceBackground />
        <div className="relative z-10 flex-1">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
